name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at 00:00 UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyGitHub
        run: pip install PyGithub

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python .github/scripts/update_stats.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update GitHub stats [bot]" || echo "No changes"
          git push
